backmarket_test/backmarket_test/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^my_app/", include("my_app.urls")),
]

backmarket_test/my_app/urls.py
from django.conf.urls import url

from my_app.views import home


app_name = "my_app"

urlpatterns = [
    url(r"^$", home, name="home"),
]

backmarket_test/my_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

backmarket_test/my_app/forms.py
from django import forms


class CityForm(forms.Form):
    city = forms.CharField()

backmarket_test/my_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import Http404

from my_app.forms import CityForm
from api_client import API_Request
from weather import parse_weather


def home(request):
    """View rendering the home page. If the request is a GET, it will display a form 
    taking a name of the city the user wants infos on. If the request is a POST, it 
    will display weather forecast informations"""

    if request.method == "POST":
        form = CityForm(request.POST)

        if form.is_valid():
            city = form.cleaned_data["city"].lower()
            api_client = API_Request(city)
            woeid = api_client.woeid

            # Checking that the api found a city
            if woeid:
                weather = api_client.get_weather()

                # Getting data for today weather

                city = parse_weather(weather).city
                country = parse_weather(weather).country
                min_temp = parse_weather(weather).min_temp
                max_temp = parse_weather(weather).max_temp
                current_temp = parse_weather(weather).current_temp
                wind_speed = parse_weather(weather).wind_speed
                humidity = parse_weather(weather).humidity

                # Getting data for 3 days weather

                city_3 = parse_weather(weather, 3).city
                country_3 = parse_weather(weather, 3).country
                min_temp_3 = parse_weather(weather, 3).min_temp
                max_temp_3 = parse_weather(weather, 3).max_temp
                wind_speed_3 = parse_weather(weather, 3).wind_speed
                humidity_3 = parse_weather(weather, 3).humidity

                sent = True

            else:
                raise Http404

    else:
        form = CityForm()

    return render(request, "my_app/home.html", locals())

backmarket_test/my_app/templates/my_app/home.html
{% load static %}

<!DOCTYPE html>

<html>

    <head>

        <title>Home</title>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/bootstrap.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/mycss.css' %}"/>

    </head>

    <body>

        <div class='container'>

            <h1>Welcome on the back market weather app</h1> 

        </div>

    {% if sent %} 

        <p> Please find the weather of {{ city }} in {{ country }} </p>
        <p> For today: </p>
            <ul>
                <li> The current temperature is {{current_temp}}°C </li>
                <li> The minimum temperature is {{min_temp}}°C</li>
                <li> The maximum temperature is {{max_temp}}°C </li>
                <li> The wind speed is {{wind_speed}} </li>
                <li> The humidity percentage is {{humidity}}% </li>

        <p> In three days: </p>
            <ul>
                <li> The minimum temperature will be {{min_temp_3}}°C</li>
                <li> The maximum temperature will be {{max_temp_3}}°C </li>
                <li> The wind speed will be {{wind_speed_3}} </li>
                <li> The humidity percentage will be {{humidity_3}}% </li>
            </ul>

    {% else %}

        <form action="{% url 'my_app:home' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}    
        <input type="submit" name="fill_content" value="Submit" />

    {% endif %}

    </body>

</html>